@extends('layouts.MainLayout')
@section('con')
    <div class="col-lg-12">
        <table class="table table-reflow table-hover table-bordered table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>ПКС-16-1</th>
                <th>ПКС-16-2</th>
                <th>ПКС-16-3</th>
                <th>КС-16-1</th>
                <th>КС-16-2</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
                <th>КС-16-3</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">5</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">6</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            <tr>
                <th scope="row">7</th>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
                <td>Исторя</td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection
